In [1]:
%cd .

/home/ducpham/Documents/Pytorch-Coding/LLMs/LLama-2



![rmsnorm](./images/rmsnorm.png)


In [2]:
import numpy as np

class RSMNorm:
    def __init__(self, embed_dim: int, esiplon = 1e-5, g: np.ndarray = None):
        """
        Khởi tạo RMSNorm
        :param embed_dim: Kích thước của vector embedding (embed_dim)
        :param epsilon: Giá trị nhỏ để tránh chia cho 0
        """
        
        self.g = g or np.ones(shape=embed_dim)
        self.embed_dim = embed_dim
        self.esiplon = esiplon

    def forward(self, x):
        rms = np.sqrt(np.mean(x ** 2, axis=-1, keepdims=True)) + self.esiplon
        x_hat = x / rms
        y = self.g * x_hat

        return y


N = 2
seq_len = 5
embed_dim = 4

mock_data = np.random.randn(N, seq_len, embed_dim)

rsmnorm = RSMNorm(embed_dim=embed_dim)
# In dữ liệu gốc
print("Input ban đầu: \n", mock_data)

# Áp dụng RoPE
x_rotated = rsmnorm.forward(x=mock_data)

# In kết quả
print("\nKết quả sau khi áp dụng RSMNorm:\n",  x_rotated)


Input ban đầu: 
 [[[-3.43513140e-01 -6.72918430e-01 -1.04812539e+00  5.69698544e-02]
  [-2.26633066e-01  5.77801120e-01  5.31673312e-01  5.73052533e-01]
  [-6.71123497e-01  1.13834147e+00 -3.95283523e-01 -1.11387074e+00]
  [ 7.58797095e-01 -1.11951553e+00 -2.87599647e-01  1.57149547e+00]
  [ 1.22324641e+00  1.23387642e+00 -9.24916051e-01  2.28491250e+00]]

 [[ 1.48017713e+00  3.49370086e-01  9.14797562e-02 -8.13545685e-02]
  [ 3.56506906e-01  2.23377502e-01 -1.07823229e-01 -6.87698398e-01]
  [-1.65978834e+00  4.12856456e-01  1.37795151e+00  1.39169058e+00]
  [-1.00767140e-01  6.11475698e-01 -7.45880068e-01 -5.53850366e-01]
  [ 1.56916729e+00 -4.38030137e-01 -2.80440122e-01 -2.88789793e-04]]]

Kết quả sau khi áp dụng RSMNorm:
 [[[-5.31210092e-01 -1.04060375e+00 -1.62082529e+00  8.80984104e-02]
  [-4.54101921e-01  1.15773309e+00  1.06530736e+00  1.14821840e+00]
  [-7.57081369e-01  1.28414088e+00 -4.45911658e-01 -1.25653593e+00]
  [ 7.25011796e-01 -1.06966931e+00 -2.74794326e-01  1.501524