In [3]:
%cd .

/home/ducpham/Documents/Pytorch-Coding/LLMs/LLama-2



![rmsnorm](./images/rmsnorm.png)


In [1]:
import numpy as np

class RSMNorm:
    def __init__(self, embed_dim: int, esiplon = 1e-5, g: np.ndarray = None):
        """
        Khởi tạo RMSNorm
        :param embed_dim: Kích thước của vector embedding (embed_dim)
        :param epsilon: Giá trị nhỏ để tránh chia cho 0
        """
        
        self.g = g or np.ones(shape=embed_dim)
        self.embed_dim = embed_dim
        self.esiplon = esiplon

    def forward(self, x):
        rms = np.sqrt(np.mean(x ** 2, axis=-1, keepdims=True)) + self.esiplon
        x_hat = x / rms
        y = self.g * x_hat

        return y


N = 2
seq_len = 5
embed_dim = 4

mock_data = np.random.randn(N, seq_len, embed_dim)

rsmnorm = RSMNorm(embed_dim=embed_dim)
# In dữ liệu gốc
print("Input ban đầu: \n", mock_data)

# Áp dụng RoPE
x_rotated = rsmnorm.forward(x=mock_data)

# In kết quả
print("\nKết quả sau khi áp dụng RSMNorm:\n",  x_rotated)


Input ban đầu: 
 [[[-0.32772083 -0.1605637  -0.56943102  0.60948492]
  [ 0.46251912 -0.04604917  0.00766852  0.46227308]
  [ 0.51020807 -1.72793938 -0.38013306  0.37363672]
  [ 0.46067156 -1.81651267  0.79305923 -0.31186489]
  [-0.41042423  0.35696675 -0.35761494  0.47272254]]

 [[ 1.53144503  0.71852416  0.6821972  -1.51452122]
  [-0.37316003  0.2917227   0.80544638 -0.78087661]
  [ 0.84235329 -0.85676978 -0.07746927  0.17458144]
  [ 0.86718475  0.23922066 -1.04321104 -1.87570978]
  [ 1.18891654 -0.96800854 -1.65356815  0.33720864]]]

Kết quả sau khi áp dụng RSMNorm:
 [[[-0.71989982 -0.35270808 -1.25086127  1.33884712]
  [ 1.41095577 -0.1404771   0.02339349  1.4102052 ]
  [ 0.54309213 -1.83930899 -0.4046335   0.39771845]
  [ 0.44753764 -1.76472321  0.77044881 -0.3029735 ]
  [-1.02028951  0.8873975  -0.88900886  1.17515929]]

 [[ 1.29190298  0.6061357   0.57549084 -1.27762632]
  [-0.61286879  0.47911815  1.3228452  -1.28249243]
  [ 1.38475369 -1.40845311 -0.12735257  0.28699632]
  [ 0.